# change the followings to match your Github username and repo name
baseurl: "/tailpages" # the name of your github repo
url: "https://cdhagmann.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "Tailpages: Tailwind + Github Pages"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Chris Hagmann
author-bio: Rails Developer # change to false to hide
author-image: 4440901.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Projects
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.cdhagmann.com/
facebook: https://facebook.cdhagmann.com/
instagram: false
github: https://github.cdhagmann.com/
linkedin: https://linkedin.cdhagmann.com/
medium: false
google-scholar: false
email: me@cdhagmann.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
